.\"/*
.\" * Copyright (C) 2012 Red Hat, Inc.
.\" *
.\" * All rights reserved.
.\" *
.\" * Author: Fabio M. Di Nitto <fabbione@kronosnet.org>
.\" *
.\" * This software licensed under GPL-2.0+, LGPL-2.0+
.\" */
.TH "KRONOSNETD" "8" "November 2012" "kronosnetd key generator." "System Administration Utilities"

.SH "NAME"
knet\-keygen \- Tool to generate keys for kronosnetd.

.SH "SYNOPSIS"
.B knet\-keygen
\fB\-o\fR <output_file> [\-s <size>]

.SH "OPTIONS"
.TP
\fB\-o\fR
Output file
.TP
\fB\-s\fR
Key size (value between 1024 and 4096 included)

.SH "SEE ALSO"
kronosnetd(8)
