.\"/*
.\" * Copyright (C) 2010-2015 Red Hat, Inc.
.\" *
.\" * All rights reserved.
.\" *
.\" * Author: Fabio M. Di Nitto <fabbione@kronosnet.org>
.\" *
.\" * This software licensed under GPL-2.0+, LGPL-2.0+
.\" */
.TH "KRONOSNETD" "8" "November 2012" "kronosnetd Usage:" "System Administration Utilities"

.SH "NAME"
kronosnetd \- libknet management daemon

.SH "DESCRIPTION"
Usage:
.PP
kronosnetd [options]

.SH "OPTIONS"

.TP
\fB\-a\fR <ipv6_addr>
Bind management VTY to ipv6_addr (default: localhost)
.TP
\fB\-b\fR <ipv4_addr>
Bind management VTY to ipv4_addr (default: localhost)
.TP
\fB\-p\fR <port>
Bind management VTY to port (default 50000)
.TP
\fB\-c\fR <file>
Use config file (default /etc/kronosnet/kronosnetd.conf)
.TP
\fB\-l\fR <file>
Use log file (default /var/log//kronosnetd.log)
.TP
\fB\-f\fR
Do not fork in background
.TP
\fB\-d\fR
Enable debugging output
.TP
\fB\-h\fR
This help
.TP
\fB\-V\fR
Print program version information

.SH "SEE ALSO"
knet-keygen(8)
